allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
overrides:
  minimatch: ^10.2.3
  glob: ^10.5.0