import type { Quotation } from '@/types';

/**
 * 内置示例报价单：用于模板编辑器的「所见即所得」预览。
 * 不依赖任何后端数据，保证做模板时即可看到真实排版效果。
 * 注意：明细字段必须放在 productSnapshot 内（与 fieldValue 取值口径一致），
 * 否则预览单元格会显示为空。
 */
export const sampleQuotation: Quotation = {
    id: 'sample',
    code: 'Q-2026-0001',
    customerName: '示例科技有限公司',
    customerContact: '张经理',
    customerAddress: '广东省深圳市南山区示例路 1 号',
    status: 'DRAFT',
    taxRate: 13,
    items: [
        {
            id: 's1',
            productSnapshot: {
                code: 'HW-SRV-001',
                name: '机架式服务器',
                brand: 'Huawei',
                model: '2288H V5',
                category: '服务器',
                description:
                    '2U 机架式，2×Xeon 4310，128GB DDR4，2×480GB SSD + 4×4TB HDD，双电源',
                unit: '台',
                tags: ['服务器', '机架式'],
                minOrderQty: 1,
                remark: '含上架服务',
            },
            quantity: 2,
            unitPrice: 38000,
            discount: 5,
            subtotal: 72200,
            displayOrder: 1,
        },
        {
            id: 's2',
            productSnapshot: {
                code: 'HW-SRV-002',
                name: '机架式服务器',
                brand: 'Huawei',
                model: '2288H V6',
                category: '服务器',
                description: '2U 机架式，2×Xeon 5318Y，256GB DDR4，4×960GB SSD',
                unit: '台',
                tags: ['服务器'],
                minOrderQty: 1,
            },
            quantity: 1,
            unitPrice: 52000,
            discount: 0,
            subtotal: 52000,
            displayOrder: 2,
        },
        {
            id: 's3',
            productSnapshot: {
                code: 'NET-SW-010',
                name: '万兆交换机',
                brand: 'H3C',
                model: 'S6800',
                category: '网络设备',
                description: '48×10GE SFP+ + 6×40GE QSFP+，含堆叠线缆',
                unit: '台',
                tags: ['网络', '交换机'],
                minOrderQty: 1,
            },
            quantity: 4,
            unitPrice: 22000,
            discount: 8,
            subtotal: 80960,
            displayOrder: 3,
        },
        {
            id: 's4',
            productSnapshot: {
                code: 'SVC-IMPL',
                name: '系统集成实施',
                brand: '自研',
                model: 'STD',
                category: '服务',
                description: '机房上架、综合布线、设备联调、系统初始化及验收交付',
                unit: '项',
                tags: ['服务'],
                minOrderQty: 1,
            },
            quantity: 1,
            unitPrice: 30000,
            discount: 0,
            subtotal: 30000,
            displayOrder: 4,
        },
    ],
    totalAmount: 235160,
    taxAmount: 30570.8,
    finalAmount: 265730.8,
    version: 1,
    versionGroupId: 'sample',
    templateId: null,
    template: null,
    createdAt: '2026-08-20T09:00:00.000Z',
    updatedAt: '2026-08-20T09:00:00.000Z',
};
